version: "3"
services:

  balancer:
    image: uday0docker/pr-balancer:init
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - internal

  frontend:
    image: uday0docker/pr-frontend:init
    volumes:
      - ./frontend:/app
    networks:
      - internal

  backend:
    image: uday0docker/pr-backend:init
    volumes:
      - ./backend:/app
    environment:
      - PORT=4000
      - DB_URI=mongodb://db/development
    depends_on:
      - db
    networks:
      - internal

  db:
    image: uday0docker/pr-db:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/configdb:/data/configdb
      - ./db/db:/data/db
    networks:
      - internal

networks:
  internal:
